default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db
  username: postgres

development:
  <<: *default
  database: github_watcher_development

test:
  adapter: postgresql
  encoding: utf8
  database: github_watcher_test
  pool: 5
  username: yasfi
  password: yasfi
  host: localhost